"""migration3

Revision ID: 86b67b264c8b
Revises: d1627948e9a1
Create Date: 2025-05-17 09:08:29.886912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86b67b264c8b'
down_revision: Union[str, None] = 'd1627948e9a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resumes', 'compensation',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resumes', 'compensation',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
