"""migration2

Revision ID: d1627948e9a1
Revises: 3cb23875ebf3
Create Date: 2025-05-17 09:05:46.288157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1627948e9a1'
down_revision: Union[str, None] = '3cb23875ebf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resumes', 'compensation',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('resumes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("TIMEZONE('utc', now())"),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resumes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('resumes', 'compensation',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
